
-- --------------------------------------------------------

--
-- Table structure for table `GameItems`
--

CREATE TABLE `GameItems` (
  `ItemId` int NOT NULL,
  `ItemName` varchar(256) COLLATE utf8mb4_general_ci NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Dumping data for table `GameItems`
--

INSERT INTO `GameItems` (`ItemId`, `ItemName`) VALUES
(1, 'apple core'),
(2, 'banana peel'),
(3, 'compostable bowl'),
(4, 'small branches'),
(5, 'moldy bread'),
(6, 'moldy carrots'),
(7, 'cheese'),
(8, 'chicken bones'),
(9, 'coffee filter'),
(10, 'eggshells'),
(11, 'fish bones'),
(12, 'dead flowers'),
(13, 'food scraps'),
(14, 'moldy grapes'),
(15, 'weeds'),
(16, 'grass clippings'),
(17, 'untreated wood'),
(18, 'meat'),
(19, 'soiled napkin'),
(20, 'orange peel'),
(21, 'used paper towel'),
(22, 'pasta'),
(23, 'moldy pear'),
(24, 'soiled pizza box'),
(25, 'moldy potato'),
(26, 'rice'),
(27, 'shrimp shells'),
(28, 'moldy squash'),
(29, 'fiber takeout box'),
(30, 'fiber takeout box'),
(31, 'tea bag'),
(32, 'twigs'),
(33, 'compostable utensils'),
(34, 'veggie scraps'),
(35, 'basketball'),
(36, 'broken planter'),
(37, 'bubble envelope'),
(38, 'plastic-lined envelope'),
(39, 'bubble wrap'),
(40, 'candy wrapper'),
(41, 'snack bag'),
(42, 'coated coffee cup'),
(43, 'coffee pod / k-cup'),
(44, 'broken glass'),
(45, 'disposable gloves'),
(46, 'plastic hanger'),
(47, 'juice box'),
(48, 'juice pouch'),
(49, 'sanitary mask'),
(50, 'milk carton'),
(51, 'broken mirror'),
(52, 'ceramic mug'),
(53, 'styrofoam peanuts'),
(54, 'pet waste'),
(55, 'plastic bag'),
(56, 'plastic wrap'),
(57, 'broken plate'),
(58, 'snack wrappers'),
(59, 'coated soda cup'),
(60, 'coated soda cup'),
(61, 'plastic straws'),
(62, 'styrofoam coffee cup'),
(63, 'toothpaste tube'),
(64, 'broken plastic toy'),
(65, 'treated lumber'),
(66, 'plastic utensils'),
(67, 'vaccuum hose'),
(68, 'sanitary wipes'),
(69, 'ziploc bag'),
(70, 'paper'),
(71, 'brown glass bottle'),
(72, 'aluminum can'),
(73, 'cardboard'),
(74, 'cereal box'),
(75, 'clamshell'),
(76, 'detergent bottle'),
(77, 'plastic jugs'),
(78, 'aluminum foil'),
(79, 'glass bottle'),
(80, 'glass jars'),
(81, 'green glass bottle'),
(82, 'plastic milk jug'),
(83, 'crushed plastic jug'),
(84, 'junk mail'),
(85, 'paper'),
(86, 'magazines'),
(87, 'mail'),
(88, 'newspaper'),
(89, 'pie tin'),
(90, 'plastic bottles'),
(91, 'shampoo bottle'),
(92, 'soda cans'),
(93, 'cardboard tubes'),
(94, 'plastic water bottle'),
(95, 'yogurt cup'),
(96, 'batteries'),
(97, 'bleach container'),
(98, 'old furniture'),
(99, 'plastic furniture'),
(100, 'broken chair'),
(101, 'wooden furniture'),
(102, 'chemical spray bottle'),
(103, 'broken coffee maker'),
(104, 'broken computer'),
(105, 'game controller'),
(106, 'desk chair'),
(107, 'office chair'),
(108, 'bulky furniture'),
(109, 'assorted wires'),
(110, 'fire extinguisher'),
(111, 'broken fire alarm'),
(112, 'broken refrigerator'),
(113, 'head phones'),
(114, 'herbicide spray bottle'),
(115, 'broken laptop'),
(116, 'light bulbs'),
(117, 'medication'),
(118, 'broken microwave'),
(119, 'used motor oil'),
(120, 'used motor oil filter'),
(121, 'leftover paint'),
(122, 'old mobile phone'),
(123, 'fuel canister'),
(124, 'speakers'),
(125, 'small electronics'),
(126, 'cleaner bottle'),
(127, 'syringe'),
(128, 'television'),
(129, 'large appliance');
